### ISSUE TITLE
Static shortcurt shows toast "App isn't installed."

### ISSUE THREAD

**Issue by TheHighriser** [googlesamples/android-AppShortcuts#7]
I have tested the application on an emulator with API 25. When I press the static shortcut "Add a new website", a toast is shown by the System : "App isn't installed."

![screenshot_1481635247](https://cloud.githubusercontent.com/assets/15047205/21141826/93a8d76c-c13f-11e6-84bc-1e47ee7e11dd.png)

**Comment by LeoYe168** [comment]
How to solve this problem ？

**Comment by TheHighriser** [comment]
This is described in here: https://github.com/googlesamples/android-AppShortcuts/issues/2

"the solution would be to replace the android:targetPackage with the applicationId from build.gradle and android:targetClass should have the full package name with the class name that is different from applicationId"

**Comment by LeoYe168** [comment]
thank you

**Comment by naitiksoni92** [comment]
@TheHighriser  Still not working!
